name: Inspection & Test
on:
  pull_request:
    branches:
      - "master"
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code on the runner
      - uses: actions/checkout@v3
      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies
      - run: npm ci
      # Run tests
      - run: npm test
